// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: task_service.proto

package task_service_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_TASK_TYPE_CHECKED     TaskType = 1
	TaskType_TASK_TYPE_TIMED       TaskType = 2
	TaskType_TASK_TYPE_PARENT      TaskType = 3
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_CHECKED",
		2: "TASK_TYPE_TIMED",
		3: "TASK_TYPE_PARENT",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"TASK_TYPE_CHECKED":     1,
		"TASK_TYPE_TIMED":       2,
		"TASK_TYPE_PARENT":      3,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_service_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_task_service_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{0}
}

type Reoccurrence int32

const (
	Reoccurrence_REOCCURRENCE_UNSPECIFIED   Reoccurrence = 0
	Reoccurrence_REOCCURRENCE_NOT_REPEATING Reoccurrence = 1
	Reoccurrence_REOCCURRENCE_DAILY         Reoccurrence = 2
	Reoccurrence_REOCCURRENCE_WEEKLY        Reoccurrence = 3
)

// Enum value maps for Reoccurrence.
var (
	Reoccurrence_name = map[int32]string{
		0: "REOCCURRENCE_UNSPECIFIED",
		1: "REOCCURRENCE_NOT_REPEATING",
		2: "REOCCURRENCE_DAILY",
		3: "REOCCURRENCE_WEEKLY",
	}
	Reoccurrence_value = map[string]int32{
		"REOCCURRENCE_UNSPECIFIED":   0,
		"REOCCURRENCE_NOT_REPEATING": 1,
		"REOCCURRENCE_DAILY":         2,
		"REOCCURRENCE_WEEKLY":        3,
	}
)

func (x Reoccurrence) Enum() *Reoccurrence {
	p := new(Reoccurrence)
	*p = x
	return p
}

func (x Reoccurrence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reoccurrence) Descriptor() protoreflect.EnumDescriptor {
	return file_task_service_proto_enumTypes[1].Descriptor()
}

func (Reoccurrence) Type() protoreflect.EnumType {
	return &file_task_service_proto_enumTypes[1]
}

func (x Reoccurrence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reoccurrence.Descriptor instead.
func (Reoccurrence) EnumDescriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{1}
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TaskType               `protobuf:"varint,1,opt,name=type,proto3,enum=TaskType" json:"type,omitempty"`
	ParentId      *string                `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Reoccurrence  Reoccurrence           `protobuf:"varint,5,opt,name=reoccurrence,proto3,enum=Reoccurrence" json:"reoccurrence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *CreateTaskRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetReoccurrence() Reoccurrence {
	if x != nil {
		return x.Reoccurrence
	}
	return Reoccurrence_REOCCURRENCE_UNSPECIFIED
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{1}
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_task_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CompleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskResponse) Reset() {
	*x = CompleteTaskResponse{}
	mi := &file_task_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskResponse) ProtoMessage() {}

func (x *CompleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{3}
}

var File_task_service_proto protoreflect.FileDescriptor

const file_task_service_proto_rawDesc = "" +
	"\n" +
	"\x12task_service.proto\"\xcb\x01\n" +
	"\x11CreateTaskRequest\x12\x1d\n" +
	"\x04type\x18\x01 \x01(\x0e2\t.TaskTypeR\x04type\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x121\n" +
	"\freoccurrence\x18\x05 \x01(\x0e2\r.ReoccurrenceR\freoccurrenceB\f\n" +
	"\n" +
	"_parent_id\"\x14\n" +
	"\x12CreateTaskResponse\".\n" +
	"\x13CompleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x16\n" +
	"\x14CompleteTaskResponse*g\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_TYPE_CHECKED\x10\x01\x12\x13\n" +
	"\x0fTASK_TYPE_TIMED\x10\x02\x12\x14\n" +
	"\x10TASK_TYPE_PARENT\x10\x03*}\n" +
	"\fReoccurrence\x12\x1c\n" +
	"\x18REOCCURRENCE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aREOCCURRENCE_NOT_REPEATING\x10\x01\x12\x16\n" +
	"\x12REOCCURRENCE_DAILY\x10\x02\x12\x17\n" +
	"\x13REOCCURRENCE_WEEKLY\x10\x032\x85\x01\n" +
	"\vTaskService\x127\n" +
	"\n" +
	"CreateTask\x12\x12.CreateTaskRequest\x1a\x13.CreateTaskResponse\"\x00\x12=\n" +
	"\fCompleteTask\x12\x14.CompleteTaskRequest\x1a\x15.CompleteTaskResponse\"\x00B<Z:github.com/SimonasKalpokas/todo_server/task_service_protosb\x06proto3"

var (
	file_task_service_proto_rawDescOnce sync.Once
	file_task_service_proto_rawDescData []byte
)

func file_task_service_proto_rawDescGZIP() []byte {
	file_task_service_proto_rawDescOnce.Do(func() {
		file_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_service_proto_rawDesc), len(file_task_service_proto_rawDesc)))
	})
	return file_task_service_proto_rawDescData
}

var file_task_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_task_service_proto_goTypes = []any{
	(TaskType)(0),                // 0: TaskType
	(Reoccurrence)(0),            // 1: Reoccurrence
	(*CreateTaskRequest)(nil),    // 2: CreateTaskRequest
	(*CreateTaskResponse)(nil),   // 3: CreateTaskResponse
	(*CompleteTaskRequest)(nil),  // 4: CompleteTaskRequest
	(*CompleteTaskResponse)(nil), // 5: CompleteTaskResponse
}
var file_task_service_proto_depIdxs = []int32{
	0, // 0: CreateTaskRequest.type:type_name -> TaskType
	1, // 1: CreateTaskRequest.reoccurrence:type_name -> Reoccurrence
	2, // 2: TaskService.CreateTask:input_type -> CreateTaskRequest
	4, // 3: TaskService.CompleteTask:input_type -> CompleteTaskRequest
	3, // 4: TaskService.CreateTask:output_type -> CreateTaskResponse
	5, // 5: TaskService.CompleteTask:output_type -> CompleteTaskResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_task_service_proto_init() }
func file_task_service_proto_init() {
	if File_task_service_proto != nil {
		return
	}
	file_task_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_service_proto_rawDesc), len(file_task_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_service_proto_goTypes,
		DependencyIndexes: file_task_service_proto_depIdxs,
		EnumInfos:         file_task_service_proto_enumTypes,
		MessageInfos:      file_task_service_proto_msgTypes,
	}.Build()
	File_task_service_proto = out.File
	file_task_service_proto_goTypes = nil
	file_task_service_proto_depIdxs = nil
}
