// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type Reoccurrence string

const (
	ReoccurrenceNotrepeating Reoccurrence = "not repeating"
	ReoccurrenceDaily        Reoccurrence = "daily"
	ReoccurrenceWeekly       Reoccurrence = "weekly"
)

func (e *Reoccurrence) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Reoccurrence(s)
	case string:
		*e = Reoccurrence(s)
	default:
		return fmt.Errorf("unsupported scan type for Reoccurrence: %T", src)
	}
	return nil
}

type NullReoccurrence struct {
	Reoccurrence Reoccurrence
	Valid        bool // Valid is true if Reoccurrence is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReoccurrence) Scan(value interface{}) error {
	if value == nil {
		ns.Reoccurrence, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Reoccurrence.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReoccurrence) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Reoccurrence), nil
}

type TaskType string

const (
	TaskTypeChecked TaskType = "checked"
	TaskTypeTimed   TaskType = "timed"
	TaskTypeParent  TaskType = "parent"
)

func (e *TaskType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskType(s)
	case string:
		*e = TaskType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskType: %T", src)
	}
	return nil
}

type NullTaskType struct {
	TaskType TaskType
	Valid    bool // Valid is true if TaskType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskType), nil
}

type Task struct {
	ID           string
	Name         string
	Description  string
	ParentID     *string
	LastDoneOn   *time.Time
	Reoccurrence Reoccurrence
	Type         TaskType
	Index        int32
}
