// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"time"
)

const completeTask = `-- name: CompleteTask :exec
UPDATE tasks
SET last_done_on = NOW()
WHERE id = $1
`

func (q *Queries) CompleteTask(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, completeTask, id)
	return err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (
	id, name, description, parent_id, last_done_on, reoccurrence, type, index
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateTaskParams struct {
	ID           string
	Name         string
	Description  string
	ParentID     *string
	LastDoneOn   *time.Time
	Reoccurrence Reoccurrence
	Type         TaskType
	Index        int32
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.Exec(ctx, createTask,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ParentID,
		arg.LastDoneOn,
		arg.Reoccurrence,
		arg.Type,
		arg.Index,
	)
	return err
}

const listTasks = `-- name: ListTasks :many
SELECT id, name, description, parent_id, last_done_on, reoccurrence, type, index FROM tasks
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.LastDoneOn,
			&i.Reoccurrence,
			&i.Type,
			&i.Index,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
